version: "3.8"

services:
  app:
    image: towfiqi/serpbear:latest
    restart: always
    ports:
      - 172.17.0.1:3333:3000
    environment:
      - USER=admin
      - PASSWORD=0123456789
      - SECRET=4715aed3216f7b0a38e6b534a958362654e96d10fbc04700770d572af3dce43625dd
      - APIKEY=5saedXklbslhnapihe2pihp3pih4fdnakhjwq5
      - NEXT_PUBLIC_APP_URL=https://${CI_CD_DOMAIN}
    volumes:
      - serpbear_appdata:/app/data

volumes:
  serpbear_appdata:
    driver: local
    driver_opts:
     type: none
     device: ${PWD}/data
     o: bind

