version: "3.8"

services:
  app:
    image: towfiqi/serpbear:${SOFTWARE_VERSION_TAG}
    restart: always
    ports:
      - 172.17.0.1:3333:3000
    environment:
      - USER=admin
      - PASSWORD=${ADMIN_PASSWORD}
      - SECRET=${ADMIN_PASSWORD}
      - APIKEY=${ADMIN_PASSWORD}
      - NEXT_PUBLIC_APP_URL=https://${CI_CD_DOMAIN}
      - SESSION_DURATION=24
    volumes:
      - serpbear_appdata:/app/data

volumes:
  serpbear_appdata:
    driver: local
    driver_opts:
     type: none
     device: ${PWD}/data
     o: bind

